name: ParaDB (api 2025-03-03)

search_url: |
  ~'https://paradb.net/api/maps?' ||
  'query=' || encodeURIComponent(query) ||
  '&limit=' || pageSize ||
  '&offset=' || ((page - 1) * pageSize) ||
  '&sort=' || case(
    sortBy,
    ['artist', 'title', 'duration'],
    ['author', 'name', 'length'],
    'submissionDate'
  ) ||
  '&sortDirection=' || sortDirection

response:
  songs_array: ~response.maps
  serializer: msgpackr

  fields:
    id: ~song.id
    uploadedAt: ~song.submissionDate
    uploadedBy: ~song.author
    title: ~song.title
    artist: ~song.artist
    downloads: ~song.downloadCount
    coverUrl: ~'https://paradb.net/covers/' || song.id || '/' || song.albumArt
    difficulties: |
      ~
      map(
        caseFn(
          ['Easy','Medium', 'Hard', 'Expert'],
          ['easy', 'medium', 'hard','expert'],
          'easy'
        ),
        map(
          getFn('difficultyName'),
          song.difficulties
        )
      )
