display_name: ParaDB (api 2025-03-03)
name: paradb

search_url: |
  ~'https://paradb.net/api/maps?' ||
  'query=' || encodeURIComponent(query) ||
  '&limit=' || pageSize ||
  '&offset=' || ((page - 1) * pageSize) ||
  '&sort=' || 
  case(
    sortBy,
    ['uploadedAt', 'title', 'artist', 'uploadedBy', 'downloads'],
    ['submissionDate', 'title', 'artist', 'author', 'downloadCount']
  ) ||
  '&sortDirection=' || sortDirection

response:
  songs_array: ~response.maps
  serializer: msgpackr

  fields:
    id: ~song.id
    uploadedAt: ~song.submissionDate
    uploadedBy: ~song.author
    title: ~song.title
    artist: ~song.artist
    downloads: ~song.downloadCount
    coverUrl: ~'https://paradb.net/covers/' || song.id || '/' || song.albumArt
    difficulties: |
      ~
      map(
        getFn('difficultyName'),
        song.difficulties
      )
